In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version:" + str(1000*(toc-tic))+"ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]

toc = time.time()
print(c)
print("Non vectorized version (for-loop):" + str(1000*(toc-tic))+"ms")
#vectorized version works almost 300 times faster!

249978.2376694217
Vectorized version:2.002239227294922ms
249978.23766941106
Non vectorized version (for-loop):510.9977722167969ms


# Broadcasting Example:

In [4]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## Notes on Numpy/Python vectors

In [9]:
a = np.random.randn(5)
print(a)

[-0.78960839 -0.40642885  0.74881355 -0.50866349 -0.33304368]


In [11]:
print(a.shape)
#Rank 1 array

(5,)


In [12]:
print(a.T)
#maintains same shape

[-0.78960839 -0.40642885  0.74881355 -0.50866349 -0.33304368]


In [15]:
print(np.dot(a,a.T))
#you get back a number

1.7190441860877181


### Using a shape with higher rank

In [17]:
a = np.random.randn(5,1)
print(a)

[[ 2.07466832]
 [ 3.36173754]
 [ 0.64705019]
 [-0.42750859]
 [-0.28801993]]


In [18]:
print(a.T)

[[ 2.07466832  3.36173754  0.64705019 -0.42750859 -0.28801993]]


In [19]:
print(np.dot(a,a.T))

[[ 4.30424863  6.97449037  1.34241453 -0.88693852 -0.59754582]
 [ 6.97449037 11.30127929  2.17521291 -1.43717167 -0.9682474 ]
 [ 1.34241453  2.17521291  0.41867395 -0.27661951 -0.18636335]
 [-0.88693852 -1.43717167 -0.27661951  0.18276359  0.12313099]
 [-0.59754582 -0.9682474  -0.18636335  0.12313099  0.08295548]]
