In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version:" + str(1000*(toc-tic))+"ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]

toc = time.time()
print(c)
print("Non vectorized version (for-loop):" + str(1000*(toc-tic))+"ms")
#vectorized version works almost 300 times faster!

250103.83843567665
Vectorized version:1.0030269622802734ms
250103.8384356825
Non vectorized version (for-loop):518.9995765686035ms


# Broadcasting Example:

In [4]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## Notes on Numpy/Python vectors

In [7]:
a = np.random.randn(5)
print(a)

[-2.20928873 -0.84936877  0.43558676 -0.95267596 -0.75491445]


In [8]:
print(a.shape)
#Rank 1 array

(5,)


In [9]:
print(a.T)
#maintains same shape

[-2.20928873 -0.84936877  0.43558676 -0.95267596 -0.75491445]


In [10]:
print(np.dot(a,a.T))
#you get back a number

7.26960710902738


### Using a shape with higher rank

In [11]:
a = np.random.randn(5,1)
print(a)

[[-1.38052236]
 [ 1.01835972]
 [-1.16932992]
 [-1.19981061]
 [ 1.08666713]]


In [12]:
print(a.T)

[[-1.38052236  1.01835972 -1.16932992 -1.19981061  1.08666713]]


In [13]:
print(np.dot(a,a.T))

[[ 1.90584199 -1.40586837  1.6142861   1.65636538 -1.50016828]
 [-1.40586837  1.03705653 -1.19079849 -1.2218388   1.10661804]
 [ 1.6142861  -1.19079849  1.36733245  1.40297444 -1.27067239]
 [ 1.65636538 -1.2218388   1.40297444  1.4395455  -1.30379476]
 [-1.50016828  1.10661804 -1.27067239 -1.30379476  1.18084546]]


In [16]:
a = np.array([[[1],[2]],[[3],[4]]])
print(a.shape)

(2, 2, 1)


In [21]:
a=np.random.randn(4,3)

b=np.random.randn(3,2)

c = a * b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [24]:
a=np.random.randn(3,4)

b=np.random.randn(4,1)

c= a*b.T
print(c.shape)

(3, 4)
